# Generated by Django 4.2.23 on 2025-06-30 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codesample',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='codesample',
            name='complexity',
            field=models.CharField(blank=True, help_text="Big O notation, e.g., 'n log n'", max_length=50),
        ),
        migrations.AddField(
            model_name='codesample',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='codesample',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='codesample',
            name='example_usage',
            field=models.TextField(blank=True, help_text='Example of how to use the code'),
        ),
        migrations.AddField(
            model_name='codesample',
            name='explanation',
            field=models.TextField(blank=True, help_text='Detailed explanation of the code'),
        ),
        migrations.AddField(
            model_name='codesample',
            name='filename',
            field=models.CharField(blank=True, help_text='Optional filename for the code', max_length=100),
        ),
        migrations.AddField(
            model_name='codesample',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to GitHub repository'),
        ),
        migrations.AddField(
            model_name='codesample',
            name='lines_of_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codesample',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='codesample',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='codesample',
            name='usage_instructions',
            field=models.TextField(blank=True, help_text='How to use this code'),
        ),
        migrations.AlterField(
            model_name='codesample',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html-css', 'HTML/CSS'), ('django', 'Django'), ('sql', 'SQL'), ('bash', 'Bash'), ('json', 'JSON'), ('algorithms', 'Algorithms'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='codesample',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
    ]
