# Generated by Django 4.2.23 on 2025-08-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_codesample_options_codesample_complexity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesample',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
